apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: read-workspace
  namespace: tekton-pipelines
spec:
  params:
  - name: PATH_CONTEXT
    type: string
    default: "."
  workspaces:
    - name: local-ws
  steps:
    - name: list-files
      image: ubuntu
      script: ls -a $(workspaces.local-ws.path)/$(params.PATH_CONTEXT)
