AWSTemplateFormatVersion: 2010-09-09
Description: ACFS3 - S3 Static site with CF and ACM (uksb-1qnk6ni7b) (version:v0.5)

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: ServiceMetaData
        Parameters:
          - AppkubeDepartment
          - AppkubeProduct
          - AppkubeEnvironment
          - AppkubeService

Mappings:
  Solution:
    Constants:
      Version: 'v0.9'

Rules:
  OnlyUsEast1:
    Assertions:
      - Assert:
          Fn::Equals:
            - !Ref AWS::Region
            - us-east-1
        AssertDescription: |
          This template can only be deployed in the us-east-1 region.
          This is because the ACM Certificate must be created in us-east-1

Parameters:
  AppkubeDepartment:
    Type: String
  AppkubeProduct:
    Type: String
  AppkubeEnvironment:
    Type: String
  AppkubeService:
    Type: String

Resources:
  CustomResourceStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ./custom-resource.yaml
      Tags:
        - Key: Solution
          Value: ACFS3
        - Key: AppkubeDepartment
          Value: !Ref AppkubeDepartment
        - Key: AppkubeProduct
          Value: !Ref AppkubeProduct
        - Key: AppkubeEnvironment
          Value: !Ref AppkubeEnvironment
        - Key: AppkubeService
          Value: !Ref AppkubeService
      Parameters:
        AppkubeDepartment: !Ref AppkubeDepartment
        AppkubeProduct: !Ref AppkubeProduct
        AppkubeEnvironment: !Ref AppkubeEnvironment
        AppkubeService: !Ref AppkubeService
  
Outputs:
  SolutionVersion:
    Value: !FindInMap [Solution, Constants, Version]
  CopyFunction:
    Description: S3 helper function
    Value: !GetAtt CustomResourceStack.Outputs.CopyFunction
  S3BucketLogs:
    Description: Logging bucket
    Value: !GetAtt CustomResourceStack.Outputs.S3BucketLogs
  S3BucketRoot:
    Description: Website bucket
    Value: !GetAtt CustomResourceStack.Outputs.S3BucketRoot
  S3BucketLogsName:
    Description: Logging bucket name
    Value: !GetAtt CustomResourceStack.Outputs.S3BucketLogsName
  S3BucketRootName:
    Description: Website bucket name
    Value: !GetAtt CustomResourceStack.Outputs.S3BucketRootName